// fundraiserOnboarding.ts — helpers for the FundraiserOnboarding wizard +
// the existing FundraiserDashboard. Stripe Connect is intentionally NOT
// wired here — payout_status defaults to 'pending_setup' on every new
// fundraiser_organizations row.

import { supabase } from './supabase'
import type {
  FundraiserOrgType,
  FundraiserCampaignStatus,
} from '../types'

// ── Organization ─────────────────────────────────────────────────────────────

export interface CreateOrganizationInput {
  userId:            string
  name:              string
  organizationType:  FundraiserOrgType
  contactName:       string
  contactEmail:      string
  contactPhone?:     string
  addressLine1?:     string
  addressCity?:      string
  addressState?:     string
  addressZip?:       string
  einOrTaxId?:       string
}

export interface CreateOrganizationResult {
  ok:        boolean
  orgId?:    string
  error?:    string
}

export async function createFundraiserOrganization(
  input: CreateOrganizationInput,
): Promise<CreateOrganizationResult> {
  if (!input.name.trim())          return { ok: false, error: 'Organization name is required' }
  if (!input.contactEmail.trim())  return { ok: false, error: 'Contact email is required' }
  if (!input.contactName.trim())   return { ok: false, error: 'Contact name is required' }

  const { data, error } = await supabase
    .from('fundraiser_organizations')
    .insert({
      created_by:           input.userId,
      name:                 input.name.trim(),
      organization_type:    input.organizationType,
      contact_name:         input.contactName.trim(),
      contact_email:        input.contactEmail.trim().toLowerCase(),
      contact_phone:        input.contactPhone?.trim() || null,
      address_line1:        input.addressLine1?.trim() || null,
      address_city:         input.addressCity?.trim() || null,
      address_state:        input.addressState?.trim() || null,
      address_zip:          input.addressZip?.trim() || null,
      ein_or_tax_id:        input.einOrTaxId?.trim() || null,
      // payout_status defaults to 'pending_setup' server-side — Stripe deferred
    })
    .select('id')
    .single()

  if (error) return { ok: false, error: error.message }
  return { ok: true, orgId: data?.id as string }
}

// ── Campaign ─────────────────────────────────────────────────────────────────

export interface CreateCampaignInput {
  userId:               string
  organizationId:       string
  name:                 string
  description?:         string
  goalAmount:           number
  participantEstimate?: number
  startDate?:           string  // YYYY-MM-DD
  endDate?:             string
}

export interface CreateCampaignResult {
  ok:           boolean
  campaignId?:  string
  code?:        string  // auto-generated by trg_campaign_code
  error?:       string
}

export async function createFundraiserCampaign(
  input: CreateCampaignInput,
): Promise<CreateCampaignResult> {
  if (!input.name.trim())         return { ok: false, error: 'Campaign name is required' }
  if (input.goalAmount < 0)       return { ok: false, error: 'Goal amount cannot be negative' }

  const { data, error } = await supabase
    .from('fundraiser_campaigns')
    .insert({
      created_by:           input.userId,
      organization_id:      input.organizationId,
      name:                 input.name.trim(),
      description:          input.description?.trim() || null,
      goal_amount:          input.goalAmount,
      participant_estimate: input.participantEstimate ?? 0,
      start_date:           input.startDate ?? null,
      end_date:             input.endDate ?? null,
      // code auto-generated by ensure_campaign_code trigger
      // status defaults to 'draft'
    })
    .select('id, code')
    .single()

  if (error) return { ok: false, error: error.message }
  return { ok: true, campaignId: data?.id as string, code: data?.code as string }
}

export async function setCampaignStatus(
  campaignId: string,
  status:     FundraiserCampaignStatus,
): Promise<{ ok: boolean; error?: string }> {
  const update: Record<string, unknown> = { status }
  if (status === 'active') update.launched_at = new Date().toISOString()
  const { error } = await supabase
    .from('fundraiser_campaigns')
    .update(update)
    .eq('id', campaignId)
  if (error) return { ok: false, error: error.message }
  return { ok: true }
}

// ── Dashboard state ──────────────────────────────────────────────────────────

export interface FundraiserDashboardState {
  organizationId:      string
  organizationName:    string
  organizationType:    string
  contactName:         string
  contactEmail:        string
  verificationStatus:  string
  payoutStatus:        string
  activeCampaignId:    string | null
  activeCampaignName:  string | null
  campaignCode:        string | null
  goalAmount:          number
  totalRaised:         number
  bagsCollected:       number
  participantEstimate: number
  actualParticipants:  number
  startDate:           string | null
  endDate:             string | null
  campaignStatus:      string | null
}

export async function loadFundraiserDashboardState(userId: string): Promise<FundraiserDashboardState | null> {
  const { data, error } = await supabase
    .from('fundraiser_dashboard_state')
    .select('*')
    .eq('created_by', userId)
    .maybeSingle()
  if (error || !data) return null

  return {
    organizationId:      data.organization_id as string,
    organizationName:    data.organization_name as string,
    organizationType:    data.organization_type as string,
    contactName:         data.contact_name as string,
    contactEmail:        data.contact_email as string,
    verificationStatus:  data.verification_status as string,
    payoutStatus:        data.payout_status as string,
    activeCampaignId:    (data.active_campaign_id as string) ?? null,
    activeCampaignName:  (data.active_campaign_name as string) ?? null,
    campaignCode:        (data.campaign_code as string) ?? null,
    goalAmount:          Number(data.goal_amount ?? 0),
    totalRaised:         Number(data.total_raised ?? 0),
    bagsCollected:       Number(data.bags_collected ?? 0),
    participantEstimate: Number(data.participant_estimate ?? 0),
    actualParticipants:  Number(data.actual_participants ?? 0),
    startDate:           (data.start_date as string) ?? null,
    endDate:             (data.end_date as string) ?? null,
    campaignStatus:      (data.campaign_status as string) ?? null,
  }
}

// ── Display helpers ──────────────────────────────────────────────────────────

export const ORG_TYPE_LABELS: Record<FundraiserOrgType, string> = {
  school:          'School',
  church:          'Church',
  nonprofit:       'Nonprofit (501c3)',
  sports_team:     'Sports Team',
  youth_program:   'Youth Program',
  community_group: 'Community Group',
  pta_pto:         'PTA / PTO',
  booster_club:    'Booster Club',
  other:           'Other',
}

export const PAYOUT_STATUS_LABELS: Record<string, string> = {
  pending_setup:     'Pending Setup',
  manual_review:     'Manual Review',
  ready_for_payout:  'Ready for Payout',
  paid:              'Paid',
}
