// notifications.ts — BayKid AI Marketing Center
import { sbInsertNotification, sbMarkNotificationRead, sbDismissNotification } from './aiMarketingDb'
// In-app notification store. Notifications are generated by:
//   • Automation rules (notify_admin action)
//   • Status transitions (pending_approval, failed)
//   • Scheduled posts firing today
//   • Follow-ups due today
// All notifications are read/dismissed client-side via localStorage.

// ── Types ─────────────────────────────────────────────────────────────────────

export type NotificationType =
  | 'pending_approval'   // Post waiting in Approval Queue
  | 'follow_up_due'      // Lead follow-up date is today or past
  | 'automation_fired'   // Automation rule triggered (notify_admin action)
  | 'scheduled_today'    // Post is scheduled to go out today
  | 'post_failed'        // Post marked as failed
  | 'lead_created'       // New lead created (automation or manual)
  | 'system'             // General admin notice

export interface AppNotification {
  id:        string
  type:      NotificationType
  title:     string
  body:      string
  ts:        string        // ISO creation timestamp
  read:      boolean
  dismissed: boolean
  /** Deep-link target: section name in AIMarketingCenter (e.g. 'queue', 'leads') */
  linkSection?: string
  /** Specific record id to highlight */
  linkId?: string
}

// ── Storage ───────────────────────────────────────────────────────────────────

const NOTIF_KEY   = 'baykid_notifications'
const MAX_NOTIFS  = 100

function safeParse(raw: string | null): AppNotification[] {
  if (!raw) return []
  try { return JSON.parse(raw) as AppNotification[] } catch { return [] }
}

export function loadNotifications(): AppNotification[] {
  return safeParse(localStorage.getItem(NOTIF_KEY))
}

export function saveNotifications(notifs: AppNotification[]): void {
  localStorage.setItem(NOTIF_KEY, JSON.stringify(notifs.slice(0, MAX_NOTIFS)))
}

// ── CRUD ──────────────────────────────────────────────────────────────────────

function newNotifId(): string {
  return `notif-${Date.now()}-${Math.random().toString(36).slice(2, 6)}`
}

export function addNotification(
  type: NotificationType,
  title: string,
  body: string,
  opts?: { linkSection?: string; linkId?: string }
): AppNotification {
  const n: AppNotification = {
    id:          newNotifId(),
    type,
    title,
    body,
    ts:          new Date().toISOString(),
    read:        false,
    dismissed:   false,
    linkSection: opts?.linkSection,
    linkId:      opts?.linkId,
  }
  const all = loadNotifications()
  all.unshift(n)
  saveNotifications(all)
  // Background sync
  sbInsertNotification(n).catch(() => {})
  return n
}

export function markRead(id: string): void {
  const all = loadNotifications()
  const n = all.find(x => x.id === id)
  if (n) { n.read = true; saveNotifications(all) }
  sbMarkNotificationRead(id).catch(() => {})
}

export function markAllRead(): void {
  const all = loadNotifications().map(n => ({ ...n, read: true }))
  saveNotifications(all)
  // Mark each unread one in Supabase
  all.filter(n => !n.dismissed).forEach(n => sbMarkNotificationRead(n.id).catch(() => {}))
}

export function dismissNotification(id: string): void {
  const all = loadNotifications()
  const n = all.find(x => x.id === id)
  if (n) { n.dismissed = true; n.read = true; saveNotifications(all) }
  sbDismissNotification(id).catch(() => {})
}

export function dismissAll(): void {
  const all = loadNotifications().map(n => ({ ...n, dismissed: true, read: true }))
  saveNotifications(all)
  all.forEach(n => sbDismissNotification(n.id).catch(() => {}))
}

// ── Query helpers ─────────────────────────────────────────────────────────────

/** Active (non-dismissed) notifications, newest first. */
export function activeNotifications(): AppNotification[] {
  return loadNotifications().filter(n => !n.dismissed)
}

/** Count of unread, non-dismissed notifications. */
export function unreadCount(): number {
  return activeNotifications().filter(n => !n.read).length
}

// ── Auto-generation from storage state ───────────────────────────────────────
// Call this once on app load (or after any status change) to ensure
// notifications reflect current reality. Uses a dedup key so we don't spam.

const GENERATED_FLAG = 'baykid_notifs_generated_at'

/**
 * Scans posts + leads in localStorage and emits notifications for:
 *  - Posts with status 'pending_approval'
 *  - Posts scheduled today
 *  - Posts with status 'failed'
 *  - Leads with followUpDate <= today
 *
 * Uses a 15-minute cooldown to avoid regenerating on every render.
 */
export function autoGenerateNotifications(): void {
  const lastRun = localStorage.getItem(GENERATED_FLAG)
  if (lastRun && Date.now() - Number(lastRun) < 15 * 60 * 1000) return
  localStorage.setItem(GENERATED_FLAG, String(Date.now()))

  const existing = loadNotifications()
  const existingLinkIds = new Set(existing.filter(n => !n.dismissed).map(n => n.linkId))

  const today = new Date().toISOString().split('T')[0]
  const newNotifs: AppNotification[] = []

  // ── Check posts ────────────────────────────────────────────────────────────
  try {
    const rawPosts = localStorage.getItem('baykid_ai_posts')
    const posts: Array<{ id: string; title?: string; status: string; scheduledFor?: string }> =
      rawPosts ? JSON.parse(rawPosts) : []

    for (const p of posts) {
      const dedupeKey = `post-${p.id}`
      if (existingLinkIds.has(dedupeKey)) continue

      if (p.status === 'pending_approval') {
        newNotifs.push({
          id: newNotifId(), type: 'pending_approval',
          title: 'Post Awaiting Approval',
          body: `"${p.title ?? 'Untitled'}" is waiting in the Approval Queue.`,
          ts: new Date().toISOString(), read: false, dismissed: false,
          linkSection: 'queue', linkId: dedupeKey,
        })
      } else if (p.status === 'failed') {
        newNotifs.push({
          id: newNotifId(), type: 'post_failed',
          title: 'Post Failed',
          body: `"${p.title ?? 'Untitled'}" encountered an error and was marked failed.`,
          ts: new Date().toISOString(), read: false, dismissed: false,
          linkSection: 'queue', linkId: dedupeKey,
        })
      } else if (p.status === 'scheduled' && p.scheduledFor) {
        const schedDate = p.scheduledFor.split('T')[0]
        if (schedDate === today) {
          newNotifs.push({
            id: newNotifId(), type: 'scheduled_today',
            title: 'Post Scheduled for Today',
            body: `"${p.title ?? 'Untitled'}" goes out today at ${new Date(p.scheduledFor).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}.`,
            ts: new Date().toISOString(), read: false, dismissed: false,
            linkSection: 'calendar', linkId: dedupeKey,
          })
        }
      }
    }
  } catch { /* ignore parse errors */ }

  // ── Check leads ────────────────────────────────────────────────────────────
  try {
    const rawLeads = localStorage.getItem('baykid_ai_leads')
    const leads: Array<{ id: string; name?: string; followUpDate?: string; status?: string }> =
      rawLeads ? JSON.parse(rawLeads) : []

    for (const l of leads) {
      if (!l.followUpDate || l.status === 'converted' || l.status === 'lost') continue
      const dedupeKey = `lead-${l.id}`
      if (existingLinkIds.has(dedupeKey)) continue
      if (l.followUpDate <= today) {
        newNotifs.push({
          id: newNotifId(), type: 'follow_up_due',
          title: 'Follow-Up Due',
          body: `Follow up with ${l.name ?? 'a lead'} is due ${l.followUpDate === today ? 'today' : `(overdue since ${l.followUpDate})`}.`,
          ts: new Date().toISOString(), read: false, dismissed: false,
          linkSection: 'leads', linkId: dedupeKey,
        })
      }
    }
  } catch { /* ignore parse errors */ }

  if (newNotifs.length > 0) {
    const all = [...newNotifs, ...existing]
    saveNotifications(all)
  }
}

// ── Icon / color meta ─────────────────────────────────────────────────────────

export const NOTIF_META: Record<NotificationType, { icon: string; color: string }> = {
  pending_approval: { icon: '⏳', color: '#fbbf24' },
  follow_up_due:    { icon: '📋', color: '#fb923c' },
  automation_fired: { icon: '⚡', color: '#00c8ff' },
  scheduled_today:  { icon: '📅', color: '#818cf8' },
  post_failed:      { icon: '⚠️', color: '#f87171' },
  lead_created:     { icon: '🎯', color: '#22c55e' },
  system:           { icon: '🔔', color: '#94a3b8' },
}
