// referral.ts — Referral-link helpers for the Invite Friends step.

import { supabase } from './supabase'

const SHARE_BASE = (typeof window !== 'undefined' ? window.location.origin : 'https://app.cbrecycling.org')

export interface ReferralInfo {
  code: string
  url:  string
}

/** Returns the authenticated user's referral_code (auto-generated by the
 *  ensure_referral_code DB trigger on profile insert). */
export async function getReferralInfo(userId: string): Promise<ReferralInfo | null> {
  const { data, error } = await supabase
    .from('profiles')
    .select('referral_code')
    .eq('id', userId)
    .maybeSingle()
  if (error || !data?.referral_code) return null
  return {
    code: data.referral_code as string,
    url:  `${SHARE_BASE}/?ref=${encodeURIComponent(data.referral_code as string)}`,
  }
}

export function buildShareMessage(code: string): string {
  return `Join me on Cyan's Brooklynn Recycling — get paid for your recycling. Use my code ${code} when you sign up: ${SHARE_BASE}/?ref=${encodeURIComponent(code)}`
}

export function smsHref(code: string): string {
  return `sms:?&body=${encodeURIComponent(buildShareMessage(code))}`
}

export function mailtoHref(code: string): string {
  const subject = 'Join me on Cyan\'s Brooklynn Recycling'
  const body    = buildShareMessage(code)
  return `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
}

export async function copyReferralLink(url: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(url)
    return true
  } catch {
    return false
  }
}

/** Uses the Web Share API where available (mobile browsers). Returns false
 *  on browsers without support so the caller can fall back to the copy UI. */
export async function nativeShare(code: string): Promise<boolean> {
  const nav = navigator as Navigator & { share?: (data: { title?: string; text?: string; url?: string }) => Promise<void> }
  if (typeof nav.share !== 'function') return false
  try {
    await nav.share({
      title: 'Cyan\'s Brooklynn Recycling',
      text:  buildShareMessage(code),
      url:   `${SHARE_BASE}/?ref=${encodeURIComponent(code)}`,
    })
    return true
  } catch {
    return false
  }
}
