import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'

function fade(a: boolean, d = 0): React.CSSProperties {
  return {
    opacity:    a ? 1 : 0,
    transform:  a ? 'translateY(0)' : 'translateY(14px)',
    transition: `opacity 0.4s ease ${d}ms, transform 0.4s ease ${d}ms`,
  }
}

const SECTIONS = [
  {
    title: '1. Commercial Account Eligibility',
    body:  'Commercial recycling accounts are available to registered businesses, nonprofits, property managers, and municipal entities. By creating a commercial account you represent that you have authority to bind the organization to these terms. Individuals may not create commercial accounts.',
  },
  {
    title: '2. Scheduled Pickup Services',
    body:  'CB Recycling will assign a commercial route driver to collect designated recycling bins or bags from your location on the schedule agreed at account setup. Pickup windows are approximate. CB Recycling reserves the right to adjust schedules due to weather, vehicle availability, or safety conditions. Commercial accounts are entitled to reasonable advance notice of schedule changes.',
  },
  {
    title: '3. Acceptable Materials',
    body:  'Only clean, dry, sortable recyclables are accepted: cardboard, paper, plastics #1–7, aluminum and steel cans, glass bottles and jars (where accepted), and electronics as specified in your service agreement. Prohibited materials include: medical waste, sharps, hazardous chemicals, biological contamination, food waste, and unmarked batteries. Loads containing prohibited materials may be refused, quarantined, or subject to a contamination fee.',
  },
  {
    title: '4. Contamination & Refusals',
    body:  'CB Recycling uses AI-assisted image analysis to flag potential contamination in incoming loads. A RED classification places the load in quarantine until reviewed by a supervisor. Contaminated loads may be returned, disposed of at the commercial account\'s expense, or subject to a contamination fee as specified in your service agreement. Repeated contamination may result in account suspension.',
  },
  {
    title: '5. Billing & Payment',
    body:  'Invoices are generated based on your service tier and any applicable per-pickup or weight-based charges specified in your service agreement. Invoices are due within 30 days of issuance. Late payments accrue interest at 1.5% per month. CB Recycling reserves the right to suspend service for accounts more than 60 days past due. Billing disputes must be submitted in writing within 14 days of invoice date.',
  },
  {
    title: '6. AI Advisory Systems',
    body:  'The BayKid platform uses AI image analysis to assist with load inspection and safety classification. AI results are advisory only. CB Recycling\'s drivers and warehouse staff retain final judgment on load acceptance. Commercial accounts may not request that AI results be suppressed or bypassed. AI classification records are retained in the audit trail for a minimum of 2 years.',
  },
  {
    title: '7. Data Sharing & Audit Access',
    body:  'Commercial account holders may request a report of their organization\'s pickup history, inspection results, and weight summaries at any time. Reports are provided within 5 business days. Data shared with commercial accounts is limited to records generated by that account. CB Recycling does not sell or share commercial account data with third parties for marketing purposes.',
  },
  {
    title: '8. Account Management',
    body:  'Commercial accounts may designate up to three authorized contacts who can request schedule changes, billing inquiries, and service modifications. Changes to authorized contacts must be submitted in writing. CB Recycling will direct all account communications to the primary contact on file.',
  },
  {
    title: '9. Service Suspension & Termination',
    body:  'CB Recycling may suspend or terminate commercial service for: repeated contamination, non-payment, safety violations, or misuse of the platform. The commercial account holder may terminate service with 30 days written notice. Outstanding invoices remain due after termination.',
  },
  {
    title: '10. Limitation of Liability',
    body:  'CB Recycling\'s liability to commercial accounts is limited to the fees paid for the service period in which the claim arose. CB Recycling is not liable for indirect, incidental, or consequential damages. Nothing in these terms limits CB Recycling\'s liability for personal injury caused by negligence or for matters where such limitation is prohibited by law.',
  },
  {
    title: '11. Governing Law',
    body:  'These terms are governed by the laws of the State of Tennessee. Disputes shall be resolved in the courts of Davidson County, Tennessee. If any provision of these terms is found unenforceable, the remaining provisions continue in effect.',
  },
  {
    title: '12. Changes to These Terms',
    body:  'CB Recycling may update these terms with 30 days notice to the primary account contact. Continued use of the service after the effective date constitutes acceptance of the updated terms.',
  },
]

export default function CommercialTermsPage() {
  const navigate  = useNavigate()
  const [a, setA] = useState(false)
  useEffect(() => { const id = requestAnimationFrame(() => setA(true)); return () => cancelAnimationFrame(id) }, [])

  return (
    <div className="relative min-h-screen flex flex-col overflow-hidden" style={{ background: 'linear-gradient(180deg, #060e24 0%, #040a1a 100%)' }}>
      <div className="pointer-events-none absolute inset-0 grid-bg" />
      <div className="pointer-events-none absolute" style={{ bottom: -60, left: -40, width: 220, height: 220, background: 'rgba(0,87,231,0.12)', filter: 'blur(60px)', borderRadius: '50%' }} />

      <header className="relative flex items-center justify-between px-4 py-3" style={{ background: 'rgba(4,10,24,0.92)', borderBottom: '1px solid rgba(0,200,255,0.12)', backdropFilter: 'blur(12px)', zIndex: 2 }}>
        <div className="flex items-center gap-3">
          <span className="text-xl font-extrabold" style={{ color: '#00c8ff' }}>BayKid</span>
          <span style={{ color: 'rgba(0,200,255,0.3)' }}>|</span>
          <span className="text-sm font-medium" style={{ color: 'rgba(255,255,255,0.45)' }}>Commercial Terms</span>
        </div>
        <button onClick={() => navigate(-1)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: 'rgba(255,255,255,0.4)', fontSize: 14 }}>
          ← Back
        </button>
      </header>

      <div className="relative flex-1 overflow-y-auto pb-20" style={{ zIndex: 1 }}>
        <div className="max-w-[520px] mx-auto px-4 pt-8 pb-8">

          <div className="mb-6" style={fade(a, 0)}>
            <span className="px-2.5 py-0.5 rounded-full text-[9px] font-bold uppercase tracking-widest mb-3 inline-block" style={{ background: 'rgba(0,200,255,0.1)', border: '1px solid rgba(0,200,255,0.3)', color: '#00c8ff' }}>
              Legal
            </span>
            <h1 className="text-2xl font-extrabold mb-1.5" style={{ color: '#ffffff' }}>Commercial Service Terms</h1>
            <p className="text-sm" style={{ color: 'rgba(255,255,255,0.45)' }}>
              Last updated May 2026. These terms apply to all commercial recycling accounts on the BayKid platform operated by CB Recycling, Nashville, TN.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            {SECTIONS.map((s, i) => (
              <div key={s.title} className="rounded-2xl p-5" style={{ background: 'rgba(0,87,231,0.07)', border: '1px solid rgba(0,200,255,0.13)', ...fade(a, 60 + i * 30) }}>
                <p style={{ fontSize: 12, fontWeight: 800, color: '#ffffff', marginBottom: 8 }}>{s.title}</p>
                <p style={{ fontSize: 12, color: 'rgba(255,255,255,0.52)', lineHeight: 1.7 }}>{s.body}</p>
              </div>
            ))}
          </div>

          <div className="rounded-2xl p-4 mt-5" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)', ...fade(a, 60 + SECTIONS.length * 30) }}>
            <p style={{ fontSize: 11, color: 'rgba(255,255,255,0.4)', textAlign: 'center', lineHeight: 1.6 }}>
              Commercial account questions?{' '}
              <a href="mailto:commercial@cbrecycling.org" style={{ color: '#00c8ff', textDecoration: 'none' }}>commercial@cbrecycling.org</a>
              {' '}· CB Recycling · Nashville, TN
            </p>
          </div>

        </div>
      </div>
    </div>
  )
}
